Issue #3130 - Fixes tests dependent on the topsites.db
So this one is a bit tricky.
I happened to upgrade the DB in my local test environment. And discovered this error.

======================================================================
FAIL: Extract list of labels from an issue body.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/unit/test_webhook.py", line 230, in test_get_issue_labels
    self.assertEqual(sorted(expected), sorted(actual))
AssertionError: Lists differ: ['browser-firefox-tablet', 'engine-gecko'] != ['browser-firefox-tablet', 'engine-gecko', 'priority-critical']

Second list contains 1 additional elements.
First extra element 2:
'priority-critical'

- ['browser-firefox-tablet', 'engine-gecko']
+ ['browser-firefox-tablet', 'engine-gecko', 'priority-critical']
?                                          +++++++++++++++++++++

The tests failing are related to using google.com domain, instead of example.com

So I went ahead here and changed google.com by example.com. It also means our tests have a dependency on the db. that's not good. We were just lucky none of our tests environment where running with a populated db so it returned no priority and the test just happened to pass.

This probably deserves another issue for running